<div>
    <div class="mb-6"><a href="{{ route('categories.index') }}" class="inline-flex items-center gap-1 text-sm text-gray-500 hover:text-gray-700"><svg class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" d="M15.75 19.5 8.25 12l7.5-7.5"/></svg> Back</a><h2 class="mt-2 text-2xl font-bold text-gray-900">Add Category</h2></div>
    <form wire:submit="save"><div class="rounded-xl bg-white p-6 shadow-sm border border-gray-100"><div class="grid grid-cols-1 gap-6 sm:grid-cols-2">
        <div><label class="block text-sm font-medium text-gray-700">Name <span class="text-red-500">*</span></label><input wire:model.live.debounce.300ms="name" type="text" class="mt-1 w-full rounded-lg border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500 sm:text-sm">@error('name')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
        <div><label class="block text-sm font-medium text-gray-700">Code <span class="text-red-500">*</span></label><input wire:model.live="code" type="text" class="mt-1 w-full rounded-lg border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500 sm:text-sm">@error('code')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
        <div class="sm:col-span-2"><label class="block text-sm font-medium text-gray-700">Description</label><textarea wire:model="description" rows="2" class="mt-1 w-full rounded-lg border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500 sm:text-sm"></textarea></div>
        <div class="flex items-center gap-3"><label class="relative inline-flex cursor-pointer items-center"><input wire:model="is_active" type="checkbox" class="peer sr-only"><div class="h-6 w-11 rounded-full bg-gray-200 after:absolute after:left-[2px] after:top-[2px] after:h-5 after:w-5 after:rounded-full after:border after:border-gray-300 after:bg-white after:transition-all peer-checked:bg-blue-600 peer-checked:after:translate-x-full peer-checked:after:border-white"></div></label><span class="text-sm font-medium text-gray-700">Active</span></div>
    </div></div>
    <div class="mt-6 flex justify-end gap-3"><a href="{{ route('categories.index') }}" class="rounded-lg border border-gray-300 bg-white px-4 py-2.5 text-sm font-medium text-gray-700 shadow-sm hover:bg-gray-50">Cancel</a><button type="submit" class="rounded-lg bg-blue-600 px-4 py-2.5 text-sm font-medium text-white shadow-sm hover:bg-blue-700">Create</button></div></form>
</div>
